baseURL = '/'
languageCode = 'en-us'
title = 'Incinta'
theme = "hyde"

[Menus]
  main = [
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/incinta/"},
      {Name = "Github", URL = "https://github.com/incinta/"},
      {Name = "TAGS", URL = "/tags/"},
      {Name = "关于", URL = "/about/"},
      {Name = "博客文章", URL = "/post/"}
      
      
  ]
 [params]
  description = "瞎写的"
  themeColor = "theme-base-0e"
  # layoutReverse = true
  disqusShortname = "spf13"
  googleAnalytics = ""
